"""Add last_modified to Equipment

Revision ID: 133f97444846
Revises: 36b2b76e26d2
Create Date: 2025-04-16 14:20:17.107105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '133f97444846'
down_revision = '36b2b76e26d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_modified', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_column('last_modified')

    # ### end Alembic commands ###
